<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Heimdall.Repository</RootNamespace>
    <AssemblyName>Heimdall.Repository</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heimdall.Core\Heimdall.Core.csproj" />
    <ProjectReference Include="..\Heimdall.Infrastructure\Heimdall.Infrastructure.csproj" />
  </ItemGroup>
</Project>
