// <auto-generated />
using System;
using Heimdall.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Heimdall.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Heimdall.Core.Entities.CodeEmbeddingChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("code_block")
                        .HasColumnName("chunk_type");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_normalized");

                    b.Property<string>("ContentRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_raw");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("embedding_model");

                    b.Property<byte[]>("EmbeddingVector")
                        .HasColumnType("bytea")
                        .HasColumnName("embedding_vector");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer")
                        .HasColumnName("end_line");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<Guid>("RepositoryVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer")
                        .HasColumnName("start_line");

                    b.Property<string>("SymbolPath")
                        .HasColumnType("text")
                        .HasColumnName("symbol_path");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryVersionId", "FilePath", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_code_embedding_chunks_version_file_chunk");

                    b.ToTable("code_embedding_chunks", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("global");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TemplateContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Variables")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ScopeType", "ScopeValue")
                        .IsUnique();

                    b.ToTable("prompt_templates", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloneUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("main");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("zh");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderRepositoryKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_repository_key");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("github")
                        .HasColumnName("provider_type");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RepoType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderType", "ProviderRepositoryKey")
                        .IsUnique()
                        .HasFilter("provider_repository_key IS NOT NULL");

                    b.HasIndex("Owner", "RepoName", "RepoType")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.RepositoryPromptOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("OverrideContent")
                        .HasColumnType("text");

                    b.Property<Guid>("PromptTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PromptTemplateId");

                    b.HasIndex("RepositoryId", "PromptTemplateId")
                        .IsUnique();

                    b.ToTable("repository_prompt_overrides", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.RepositoryVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("branch_name");

                    b.Property<string>("CommitAuthor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("commit_author");

                    b.Property<string>("CommitMessage")
                        .HasColumnType("text")
                        .HasColumnName("commit_message");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTime>("CommitTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commit_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsLatestOnBranch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_latest_on_branch");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("active")
                        .HasColumnName("source_status");

                    b.Property<string>("TreeFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tree_fingerprint");

                    b.Property<string>("VersionSourceConfidence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("exact")
                        .HasColumnName("version_source_confidence");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "BranchName", "CommitSha")
                        .IsUnique()
                        .HasDatabaseName("ix_repository_versions_repo_branch_commit");

                    b.HasIndex("RepositoryId", "BranchName", "IsLatestOnBranch")
                        .HasDatabaseName("ix_repository_versions_repo_branch_latest");

                    b.ToTable("repository_versions", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.TaskLlmCallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("CompletionTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PromptTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestPreview")
                        .HasColumnType("text");

                    b.Property<string>("ResponsePreview")
                        .HasColumnType("text");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "StepOrder")
                        .HasDatabaseName("idx_task_llm_call_logs_task");

                    b.ToTable("task_llm_call_logs", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.TaskRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("config_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("ForceRefresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("force_refresh");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProgressMessage")
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RefreshStrategy")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("refresh_strategy");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ResolvedRepositoryVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_repository_version_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ResultWikiVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_wiki_version_id");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("main")
                        .HasColumnName("source_branch");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TargetBranch")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_branch");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TotalCompletionTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalPromptTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedRepositoryVersionId");

                    b.HasIndex("ResultWikiVersionId");

                    b.HasIndex("UserId");

                    b.HasIndex("RepositoryId", "SourceBranch")
                        .IsUnique()
                        .HasDatabaseName("idx_one_running_task_per_repo_branch")
                        .HasFilter("status = 'running'");

                    b.HasIndex("RepositoryId", "SourceBranch", "TaskType")
                        .IsUnique()
                        .HasDatabaseName("idx_one_pending_task_per_repo_branch_type")
                        .HasFilter("status = 'pending'");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Viewer");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.Wiki", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("zh");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("main");

                    b.Property<Guid>("SourceRepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceRepositoryId", "SourceBranch", "Language")
                        .IsUnique();

                    b.ToTable("wikis", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiEmbeddingChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("section")
                        .HasColumnName("chunk_type");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_raw");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("embedding_model");

                    b.Property<byte[]>("EmbeddingVector")
                        .HasColumnType("bytea")
                        .HasColumnName("embedding_vector");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.Property<Guid>("WikiPageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WikiVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WikiPageId");

                    b.HasIndex("WikiVersionId", "WikiPageId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_wiki_embedding_chunks_version_page_chunk");

                    b.ToTable("wiki_embedding_chunks", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentMarkdown")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Depth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("depth");

                    b.PrimitiveCollection<string[]>("FilePaths")
                        .HasColumnType("text[]");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("medium");

                    b.Property<string>("NavTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nav_title");

                    b.Property<string>("OutlineJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("outline_json");

                    b.Property<int>("PageOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("article")
                        .HasColumnName("page_type");

                    b.Property<Guid?>("ParentPageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceCoverageJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_coverage_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("ready")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WikiId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WikiVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentPageId");

                    b.HasIndex("TaskId");

                    b.HasIndex("WikiId");

                    b.HasIndex("WikiVersionId");

                    b.ToTable("wiki_pages", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiPageRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("related_to")
                        .HasColumnName("relation_type");

                    b.Property<Guid>("SourcePageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetPageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WikiVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourcePageId");

                    b.HasIndex("TargetPageId");

                    b.HasIndex("WikiVersionId", "SourcePageId", "TargetPageId", "RelationType")
                        .IsUnique()
                        .HasDatabaseName("ix_wiki_page_relations_version_src_tgt_type");

                    b.ToTable("wiki_page_relations", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("zh")
                        .HasColumnName("language");

                    b.Property<Guid?>("PublishedWikiVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_wiki_version_id");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("default")
                        .HasColumnName("view_type");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Language", "ViewType")
                        .IsUnique()
                        .HasDatabaseName("ix_wiki_spaces_repo_lang_view");

                    b.ToTable("wiki_spaces", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_task_id");

                    b.Property<string>("GenerationMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("latest")
                        .HasColumnName("generation_mode");

                    b.Property<string>("GenerationProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("comprehensive")
                        .HasColumnName("generation_profile");

                    b.Property<bool>("IsForceRefresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_force_refresh");

                    b.Property<string>("ModelProfileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_profile_hash");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("PromptProfileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_profile_hash");

                    b.Property<Guid>("RepositoryVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("StructureJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("structure_json");

                    b.Property<string>("SummaryMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("summary_markdown");

                    b.Property<int?>("TocDepth")
                        .HasColumnType("integer")
                        .HasColumnName("toc_depth");

                    b.Property<int>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version_no");

                    b.Property<Guid>("WikiSpaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryVersionId")
                        .HasDatabaseName("ix_wiki_versions_repo_version");

                    b.HasIndex("WikiSpaceId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_wiki_versions_space_version");

                    b.ToTable("wiki_versions", (string)null);
                });

            modelBuilder.Entity("Heimdall.Core.Entities.CodeEmbeddingChunk", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.RepositoryVersion", "RepositoryVersion")
                        .WithMany()
                        .HasForeignKey("RepositoryVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepositoryVersion");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.RepositoryPromptOverride", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.PromptTemplate", "PromptTemplate")
                        .WithMany("RepositoryOverrides")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heimdall.Core.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromptTemplate");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.RepositoryVersion", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.Repository", "Repository")
                        .WithMany("RepositoryVersions")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.TaskLlmCallLog", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.TaskRecord", "Task")
                        .WithMany("LlmCallLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.TaskRecord", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.Repository", "Repository")
                        .WithMany("Tasks")
                        .HasForeignKey("RepositoryId");

                    b.HasOne("Heimdall.Core.Entities.RepositoryVersion", "ResolvedRepositoryVersion")
                        .WithMany()
                        .HasForeignKey("ResolvedRepositoryVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Heimdall.Core.Entities.WikiVersion", "ResultWikiVersion")
                        .WithMany()
                        .HasForeignKey("ResultWikiVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Heimdall.Core.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId");

                    b.Navigation("Repository");

                    b.Navigation("ResolvedRepositoryVersion");

                    b.Navigation("ResultWikiVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.Wiki", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.Repository", "SourceRepository")
                        .WithMany("Wikis")
                        .HasForeignKey("SourceRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceRepository");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiEmbeddingChunk", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.WikiPage", "WikiPage")
                        .WithMany()
                        .HasForeignKey("WikiPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heimdall.Core.Entities.WikiVersion", "WikiVersion")
                        .WithMany()
                        .HasForeignKey("WikiVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WikiPage");

                    b.Navigation("WikiVersion");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiPage", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.WikiPage", "ParentPage")
                        .WithMany("Children")
                        .HasForeignKey("ParentPageId");

                    b.HasOne("Heimdall.Core.Entities.TaskRecord", "Task")
                        .WithMany("WikiPages")
                        .HasForeignKey("TaskId");

                    b.HasOne("Heimdall.Core.Entities.Wiki", "Wiki")
                        .WithMany("Pages")
                        .HasForeignKey("WikiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heimdall.Core.Entities.WikiVersion", "WikiVersion")
                        .WithMany("WikiPages")
                        .HasForeignKey("WikiVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentPage");

                    b.Navigation("Task");

                    b.Navigation("Wiki");

                    b.Navigation("WikiVersion");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiPageRelation", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.WikiPage", "SourcePage")
                        .WithMany("SourceRelations")
                        .HasForeignKey("SourcePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heimdall.Core.Entities.WikiPage", "TargetPage")
                        .WithMany("TargetRelations")
                        .HasForeignKey("TargetPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heimdall.Core.Entities.WikiVersion", "WikiVersion")
                        .WithMany()
                        .HasForeignKey("WikiVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePage");

                    b.Navigation("TargetPage");

                    b.Navigation("WikiVersion");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiSpace", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.Repository", "Repository")
                        .WithMany("WikiSpaces")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiVersion", b =>
                {
                    b.HasOne("Heimdall.Core.Entities.RepositoryVersion", "RepositoryVersion")
                        .WithMany("WikiVersions")
                        .HasForeignKey("RepositoryVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heimdall.Core.Entities.WikiSpace", "WikiSpace")
                        .WithMany("WikiVersions")
                        .HasForeignKey("WikiSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepositoryVersion");

                    b.Navigation("WikiSpace");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.PromptTemplate", b =>
                {
                    b.Navigation("RepositoryOverrides");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.Repository", b =>
                {
                    b.Navigation("RepositoryVersions");

                    b.Navigation("Tasks");

                    b.Navigation("WikiSpaces");

                    b.Navigation("Wikis");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.RepositoryVersion", b =>
                {
                    b.Navigation("WikiVersions");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.TaskRecord", b =>
                {
                    b.Navigation("LlmCallLogs");

                    b.Navigation("WikiPages");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.User", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.Wiki", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiPage", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("SourceRelations");

                    b.Navigation("TargetRelations");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiSpace", b =>
                {
                    b.Navigation("WikiVersions");
                });

            modelBuilder.Entity("Heimdall.Core.Entities.WikiVersion", b =>
                {
                    b.Navigation("WikiPages");
                });
#pragma warning restore 612, 618
        }
    }
}
