#!/usr/bin/env bash
set -euo pipefail

echo '============================================'
echo ' Heimdall 代码仓库智能文档系统'
echo ' 架构：四层分离 (Api/Core/Infrastructure/Repository)'
echo '============================================'
echo ''
echo '后端：C# / ASP.NET Core (.NET 10)'
echo '  项目结构：'
echo '    - Heimdall.Api         API 层（控制器、中间件、DTO）'
echo '    - Heimdall.Core        业务层（实体、服务、接口）'
echo '    - Heimdall.Infrastructure 工具层（Provider、配置、仓库源）'
echo '    - Heimdall.Repository  数据层（EF Core、PostgreSQL/pgvector）'
echo ''
echo '启动命令：'
echo '  后端: dotnet run --project backend/Heimdall.Api/Heimdall.Api.csproj'
echo '  前端: cd frontend && npm run dev'
echo '  一键: cd frontend && npm run dev:all'
echo ''
echo '数据库: PostgreSQL + pgvector'
echo '  docker compose up -d postgres  # 仅启动数据库'
echo ''
echo '关键环境变量（详见 README.md）：'
echo '  HEIMDALL_CONNECTION_STRING   数据库连接字符串'
echo '  HEIMDALL_AUTH_MODE           none | jwt'
echo '  HEIMDALL_DEFAULT_PROVIDER    默认 LLM Provider'
echo '  HEIMDALL_EMBEDDER_TYPE       向量嵌入器类型'
